# Generated by Django 4.2.16 on 2026-06-13 16:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='eId', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='帳號')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('cellphone', models.CharField(max_length=10, verbose_name='手機')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('resigned_date', models.DateTimeField(blank=True, null=True, verbose_name='離職時間')),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
                'db_table': 'employees',
                'indexes': [models.Index(fields=['resigned_date'], name='idx_resigned')],
            },
            managers=[
                ('objects', accounts.models.EmployeeManager()),
            ],
        ),
    ]
