# Generated by Django 4.2.16 on 2026-05-25 16:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='帳號')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('cellphone', models.CharField(max_length=10, verbose_name='手機')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('lv', models.PositiveSmallIntegerField(choices=[(1, '員工'), (2, '業務'), (3, '主管'), (9, '管理員')], default=1, verbose_name='權限等級')),
                ('resigned_date', models.DateTimeField(blank=True, null=True, verbose_name='離職時間')),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
                'indexes': [models.Index(fields=['resigned_date'], name='idx_resigned')],
            },
            managers=[
                ('objects', accounts.models.EmployeeManager()),
            ],
        ),
    ]
