# Generated by Django 4.2.16 on 2026-06-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(db_column='sId', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='以進貨單位計', verbose_name='進貨數量')),
                ('quantity_remaining', models.IntegerField(help_text='可為負值表示超賣', verbose_name='剩餘基準單位數')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基準單位成本')),
                ('product', models.ForeignKey(db_column='pId', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.product', verbose_name='商品')),
                ('unit', models.ForeignKey(db_column='uId', on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name='進貨單位')),
            ],
            options={
                'verbose_name': '進貨批次',
                'verbose_name_plural': '進貨批次',
                'db_table': 'stocks',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'id'], name='idx_fifo_lookup')],
            },
        ),
    ]
