# Generated by Django 4.2.16 on 2026-05-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='以進貨單位計', verbose_name='進貨數量')),
                ('quantity_remaining', models.IntegerField(help_text='可為負值表示超賣', verbose_name='剩餘基準單位數')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基準單位成本')),
                ('restocked_date', models.DateField(verbose_name='進貨日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.product', verbose_name='商品')),
                ('restocked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocked_stocks', to=settings.AUTH_USER_MODEL, verbose_name='進貨人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name='進貨單位')),
            ],
            options={
                'verbose_name': '進貨批次',
                'verbose_name_plural': '進貨批次',
                'ordering': ['restocked_date', 'id'],
                'indexes': [models.Index(fields=['product', 'restocked_date', 'quantity_remaining'], name='idx_fifo_lookup')],
            },
        ),
    ]
