# Generated by Django 4.2.16 on 2026-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='custId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='客戶姓名')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='手機')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'db_table': 'customers',
                'ordering': ['id'],
            },
        ),
    ]
