# Generated by Django 4.2.16 on 2026-06-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='catId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='分類名稱')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='pId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('category', models.ForeignKey(db_column='catId', on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='分類')),
                ('created_by', models.ForeignKey(db_column='eId', on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(db_column='uId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='單位名稱')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
                'db_table': 'units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.PositiveIntegerField(help_text='此單位 = 幾個基準單位', verbose_name='換算比例')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('status', models.CharField(choices=[('active', '啟用中'), ('inactive', '已失效')], default='active', max_length=10, verbose_name='狀態')),
                ('product', models.ForeignKey(db_column='pId', on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='catalog.product', verbose_name='商品')),
                ('unit', models.ForeignKey(db_column='uId', on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='catalog.unit', verbose_name='單位')),
            ],
            options={
                'verbose_name': '商品單位定價',
                'verbose_name_plural': '商品單位定價',
                'db_table': 'product_unit',
                'ordering': ['product_id', 'unit_id'],
                'indexes': [models.Index(fields=['product', 'unit', 'status'], name='idx_active_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
    ]
