# Generated by Django 4.2.16 on 2026-05-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分類名稱')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='停用時間')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='停用時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
