# Generated by Django 4.2.16 on 2026-05-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分類名稱')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='停用時間')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_categories', to=settings.AUTH_USER_MODEL, verbose_name='停用者')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='單位名稱')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='停用時間')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_for_products', to='catalog.unit', verbose_name='基準單位')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='分類')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_products', to=settings.AUTH_USER_MODEL, verbose_name='停用者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.PositiveIntegerField(help_text='此單位 = 幾個基準單位', verbose_name='換算比例')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('status', models.CharField(choices=[('active', '啟用中'), ('inactive', '已失效')], default='active', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_units', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='catalog.product', verbose_name='商品')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='catalog.unit', verbose_name='單位')),
            ],
            options={
                'verbose_name': '商品單位定價',
                'verbose_name_plural': '商品單位定價',
                'ordering': ['product_id', 'unit_id', '-created_at'],
                'indexes': [models.Index(fields=['product', 'unit', 'status'], name='idx_active_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted_at'], name='idx_product_deleted'),
        ),
    ]
