# Generated by Django 4.2.16 on 2026-06-13 16:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='oId', primary_key=True, serialize=False)),
                ('ordered_date', models.DateTimeField(db_column='order_date', default=django.utils.timezone.now, verbose_name='訂單日期')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_by', models.ForeignKey(db_column='eId', on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(db_column='custId', on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'orders',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交單價')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交成本')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0~1 之間', max_digits=5, verbose_name='折扣率')),
                ('conversion_rate', models.PositiveIntegerField(help_text='此單位 = 幾個基準單位', verbose_name='成交換算比例')),
                ('order', models.ForeignKey(db_column='oId', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='orders.order', verbose_name='訂單')),
                ('product', models.ForeignKey(db_column='pId', on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
                'db_table': 'order_record',
                'indexes': [models.Index(fields=['order'], name='idx_record_order'), models.Index(fields=['product'], name='idx_record_product')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='idx_order_customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ordered_date'], name='idx_order_date'),
        ),
    ]
